### ISSUE TITLE
Reproduce behavior of load_sample in DSCR

### ISSUE THREAD

**Issue by mengyin** [stephenslab/dsc2#16]
Add a post-processing function or query utility, see https://github.com/stephens999/dscr/blob/master/man/load_example.Rd

**Comment by gaow** [comment]
Yes, this should certainly be implemented as a post-processing utility on data. I am actually thinking that I should get at least the lab's input on efforts related to this. Of course I'll provide a "master" data tables along the lines of #14 to start with, and I expect others to contribute **documented** R functions that extracts and re-organize information from these master data tables the way they see fit.

**Comment by gaow** [comment]
Discussed this with @road2stat and we'll initialize a `shinydsc` project.
