### ISSUE TITLE
transfer of variables through pipeline

### ISSUE THREAD

**Issue by stephens999** [stephenslab/dsc2#2]
my vision is that variables are automatically transferred through pipeline
so if a method uses a variable x it should be whatever x was generated by previous steps
of the pipeline - no need for the user to say which step generated it, as the
software will work that out for you when running the pipeline.

Example: 
you have three pipelines for testing whether difference in distribution between x and y.
first does quantile normalization of c(x,y) followed by t test, second just does t test.

so your benchmark has two different types of pipeline
scenario -> qnorm -> ttest -> score
scenario -> ttest -> score

in each case the ttest step just takes input (x,y) and outputs a p value 
but in first case (x,y) was the output of qnorm step
where in the second case (x,y) was the direct output of scenario

**Comment by gaow** [comment]
Resolved in the updated design.
