### ISSUE TITLE
dsc2 doesn't like R NA objects

### ISSUE THREAD

**Issue by dcgerard** [stephenslab/dsc2#26]
# Files
[dsc_na_error.zip](https://github.com/stephenslab/dsc2/files/350405/dsc_na_error.zip)

# Code
``` shell
dsc_na_error$ dsc exec settings.dsc
INFO: Constructing DSC from settings.dsc ...
INFO: DSC exported to settings.html
INFO: Building output database dsc_result.rds ...
INFO: Elapsed time 0.384 seconds.
ERROR: 'list' object has no attribute 'shape'
ERROR: 'list' object has no attribute 'shape'
```

Ideally, `foo` can either be a numeric or `NA`. See settings2.dsc.

**Comment by gaow** [comment]
Converted to NaN and saved to the final output. More details see comment at #25.
