### ISSUE TITLE
DSC for machine learning

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#35]
@pcarbo suggests that DSC should also target the ML community. One obvious thing to add to the appeal of DSC there is to automate cross validation.

**Comment by stephens999** [comment]
+1

**Comment by pcarbo** [comment]
Cross validation is definitely useful for **both** statisticians and ML researchers.

Cross validation for evaluation, or for optimizing a parameter? Or for both? 

I would think that simple types of cross validation (e.g., *k*-fold cross validation) should be easy to implement, unless there are aspects to your DSC2 framework that make it more complicated.

**Comment by gaow** [comment]
Both would be important ... but I think cross validation for optimizing a parameter would be converted to evaluation via writing up a separate DSC dedicated for one single method. Modularity and simplicity are the upside of this implementation. The downside is that users would have to run 2 or more DSC one after the other -- learn the best parameters from previous DSC's and manually put into the last DSC (I hate the manual part).  

There are 2 challenges as far as I can tell:

1. The interface:  we try to keep DSC interface as simple as possible. It would be great if we can design a neat CV interface and work from there. 
2. Data communication: DSC does not have any restriction on input data type and languages used for a particular computational routine. Yet DSC will provide the CV framework (function) and any function will require **non-arbitrary** form of input. Thus CV data have to be communicated in a restricted way which will contradict with what can be allowed for DSC steps (language is again not the issue as we'll eventually interface with data). 

We may use simple CV as @pcarbo suggested and a concrete example to design the interface. Not sure if we can cover this as well in the next week's meeting.

**Comment by pcarbo** [comment]
Thanks for the explanation, Gao. That makes sense to me.

**Comment by gaow** [comment]
Another relevant thought from poster session at MSDSE meeting: can we automate simple statistical ensemble methods? But I feel this is something against the 80:20 rule in software development.

**Comment by pcarbo** [comment]
Yes. Leave it for DSC3. :)

**Comment by gaow** [comment]
Good idea @pcarbo. Let's use this ticket #37
