### ISSUE TITLE
Support for cluster

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#4]
Should we interact directly with the cluster or just split jobs for users and let them take care of it?

**Comment by stephens999** [comment]
my hope was that existing tools (snakemake?) could be used for cluster submission, provided
we output the jobs in appropriate format(s).

**Comment by gaow** [comment]
Snakemake relies on shell command 'qsub' and I did not like the experience with it. Currently the "embarrassing parallel" mode is powered by [celery](http://www.celeryproject.org/), which has the potential to distribute tasks to multiple nodes on cluster once we have something like DAG, although how exactly it is done remains to be explored.

**Comment by gaow** [comment]
Will discuss and implement in the upstream `pysos` library
