### ISSUE TITLE
Interactive DSC

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#45]
I'm starting to try DSC as a prototyping tool. Here what I mean by "prototyping" is when in the developmental phase of a new model we might want to try variations of the same model by applying different simplifications or embellishments, before deciding what to code up into a software. The modular, multi-linguistic nature and implicit intermediate output feature of DSC makes it a seemingly good choice for prototyping -- by "seemingly" I mean we may need a different interface for this purpose, because compared to using DSC as a benchmark tool, prototyping is more a trial-error process on incomplete products, and a interactive interface is perhaps therefore a better choice. I have something in mind with Jupyter implementation but considering the majority users (at least from Stephens lab) are in Rstudio we might have to be more careful about this. Need to think more about this interface as I prototype with DSC for my own projects.

**Comment by stephens999** [comment]
i definitely have experience of trying to use dscr in this regard.
Also mengyin has experience I think of using dscr during prototypign
stage. I think it is valuable to think about.

A key issue is being able to deal nicely with code that does not
run, or to detect errors in code by being able to examine individual
instances (as in the load_example function in dscr)

**Comment by gaow** [comment]
For code that does not run, the command interface will give an error message along with path to the propagated version of code for users to debug and fix. For example:

```
[GW] dsc -x settings.dsc 
INFO: DSC script exported to settings.html
INFO: Constructing DSC from settings.dsc ...

DSC:   0%|                                                | 0/2 [00:00<?, ?it/s]

Error: could not find function "foo"0%|                   | 0/3 [00:00<?, ?it/s]

ERROR: Failed to execute workflow DSC%|███▋       | 1/3 [00:03<00:07,  3.61s/it]
[DSC_1 (DSC sequence 1)] RuntimeError:
	Failed to process statement sos_run('simulate:1+shrink:1+b...id = '1')\n: Failed to execute workflow simulate:1+shrink:1+beta_score:1
[simulate_1 (datamaker.R)] RuntimeError:
	Failed to execute script (ret=1). 
Please use command
    Rscript --default-packages=datasets,methods,utils,stats,grDevices,graphics  /home/gaow/GIT/software/dsc2/vignettes/ash/.sos/simulate_1_0.R
under /home/gaow/GIT/software/dsc2/vignettes/ash to test it.
[simulate:1+shrink:1+beta_score:1] RuntimeError:
	1 failed step: simulate_1 (datamaker.R)
[DSC] RuntimeError:
	1 failed step: DSC_1 (DSC sequence 1)
```

where it says

> Please use command
    Rscript --default-packages=datasets,methods,utils,stats,grDevices,graphics  /home/gaow/GIT/software/dsc2/vignettes/ash/.sos/simulate_1_0.R
under /home/gaow/GIT/software/dsc2/vignettes/ash to test it.

and difference between `simulate_1_0.R` and `datamaker.R` is that `simulat_1_0.R` has incorporated the input / output data in order to run as a stand alone script.

I envision this paradigm for DSC prototyping: users open up all codes in Rstudio and run with shinydsc the DSC commands / annotations -- which is essentially a system call wrapper of `dsc -x` and `dsc -e`. If the prototype program works successfully one can use the shinydsc viz module to explore the data, otherwise one can fix the code based on hints from this error message, run again and explore. I think at this point with the updated query mechanism ('dsc -a / -e') the shinydsc design is much simpler and we should have a draft up and running soon.

**Comment by gaow** [comment]
It is too much to ask people to use DSC in Jupyter so I gave up the Jupyter notebook plugin idea. Instead we finally got shinydsc going. On the DSC end, improved command interface and tips for interactive debugging are documented:

https://stephenslab.github.io/dsc-wiki/doc/tutorials/Debug_Tips.html

Exploratory analysis can be done with `--seed 1 --sequence "step_of_interest" `. This is the smallest element of computational unit one can possibly reach from command interface. 

#66 implements a way to deal with code that does not run. The `shinydsc` app (though still a lot to be desired from it) handles visualization. Even without shiny, one can load the output RDS from limited seeds and sequences and examine them. 

I'll chat with Mengyin on her experience with DSCR on this aspect. This issue is closed for now because I cannot think of other major ways to improve.
