### ISSUE TITLE
Output data type in extracted DSC data

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#58]
This is a continuation of discussion to the last post in #55. The question is whether we should try to polish results such as this:

```￼
> dat$An_ash_n_beta_score_result
[[1]]
[1] 0.7736099

[[2]]
[1] 0.5789447

[[3]]
[1] 0.71792

[[4]]
[1] 0.5506716

[[5]]
[1] 0.4610809

> dat$An_ash_nu_beta_score_result
[[1]]
[1] 0.7842367

[[2]]
[1] 0.5757998

[[3]]
[1] 0.7159448

[[4]]
[1] 0.5536478

[[5]]
[1] 0.4598015

```

into something like this:

```
￼> dat$An_ash_n_beta_score_result
[1] 0.7736099  0.5789447  0.71792  0.5506716 0.4610809

> dat$An_ash_nu_beta_score_result
[1] 0.7842367 0.5757998 0.7159448 0.5536478 0.4598015
```

and, if yes, how to do it properly in R. Any tips appreciated -- I'm not exactly a (modern) R savvy.

**Comment by gaow** [comment]
This R code will help generating a toy example for our discussion here:

```
eg_a = eg_b = eg_c = list()
for (i in 1:4) {
  eg_a[[i]] = runif(1)
  eg_b[[i]] = runif(4)
  eg_c[[i]] = matrix(runif(4), 2, 2)
}
```

Now with this data, it is appropriate to do `eg_a = unlist(eg_a)`, `eg_b = data.frame(eg_b)` (or not?) and I do not know how `eg_c` should be handled. I think we can ask user to choose from `unlist`, `data.frame` etc or define data processing functions in shinydsc so that users can decide what to do to transform data and use the few plotting modules shinydsc provides.

**Comment by pcarbo** [comment]
Gao, this seems like a relatively minor aspect to your interface, but you could do something like this:

```
if (all(sapply(dat,length) == 1))
  dat <- unlist(dat)
else if (all(sapply(dat,is.vector)))
  dat <- do.call(rbind,dat)
else {
  # Do nothing.
}
```

**Comment by gaow** [comment]
Thanks Peter. This is the type of advice I'm looking for!
