### ISSUE TITLE
"dot" in variable names

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#61]
In the R community "dot" can be used in variable names, e.g., `sample.size`. But this creates problems here because Python would treat `.size` a member of `sample` class. Currently DSC cannot handle these names. It is [not good practice to use "dot" ](http://r-pkgs.had.co.nz/style.html) anyways so I'll automatically create alias for them whenever I see dotted names. A warning message will be given.

**Comment by pcarbo** [comment]
I agree with this solution. I have never named variables in this way and I think it is reasonable not to expect others to do the same.

**Comment by stephens999** [comment]
it is *very* common practice...

I have started to try to avoid it myself, but only recently.
I'm not sure you can expect people not to use dot... It
could even be the case that base R functions take names
with dots in them?

Matthew

**Comment by pcarbo** [comment]
Sorry, I misread your comment, Gao. I was thinking only of the case in which the variable name starts with a dot; e.g., `.size`. Yes, Matthew is right, having a period in a name is very common; e.g. `read.csv`. I think there needs to be some way to allow for this. It doesn't need to be solved immediately, but if there is a way to provide an informative error message for now, that would be helpful.

**Comment by gaow** [comment]
Yes, the solution is to provide a warning message when dot is used in variable names, though internally I'd have to deal with replacing the dot as it does not work with Python variable names. Functions with dot would not be touched.

With these and other corner cases in practice / patches that are starting to accumulate, I feel perhaps very soon I'll have to start refactoring the DSC2 code. I always expect this coming from my past experience (thus not enough unit-tests were written). It should a few days if properly designed, but I'll have to plan for this schedule-wise.

**Comment by gaow** [comment]
Current behavior is to quit with an error message that contains a tip to bypbass this with `@ALIAS`

```
[GW] dsc test.dsc 
ERROR: Dot is not allowed for module / variable names, in x.y. Note that dotted names is not acceptable to Python and SQL. If this limitation is irrelevant to your problem, and you really cannot rename variable in your code, then at your own risk you can rename x.y to, eg, name in DSC and use @ALIAS: x.y = name.
```
