### ISSUE TITLE
A general `try ... catch` interface

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#66]
## Problem

When running a large benchmark there can be still failures in some steps with some parameters even when the script is tested on toy examples. Failures due to corner cases can be particularly annoying because they would pop up and disrupt the benchmark execution, causing related steps to fail (because of our version of DAG design). 

## Solution

It is possible to wrap the script automatically with `try ... catch` in R and `try ... except` in Python. We can add a switch `--ignore-errors` to the command interface. 

## Downside and counter measure
However this makes it difficult to track at the end of the pipeline what steps have failed. One possible way is to add automatically to the output data a variable called `BUGGY_CODE_` that stores the entire script in question for one to debug after.

**Comment by stephens999** [comment]
yes, this is an important issue... it happens a lot in practice that
things fail and we need a way to deal with it.

BTW, while debugging is important, in some cases it is other peoples
software and you have no time to debug it - the most important thing
there is that it gives answers when it can, and gives something else
(NA?) when it fails. Maybe when compiling results (eg averaging scores
across seeds) we should output
for each method what proportion of datasets it completed for, to avoid
misleading people when methods only complete on a small subset of data.

Matthew

**Comment by gaow** [comment]
> the most important thing
there is that it gives answers when it can, and gives something else
(NA?) when it fails. 

yes I'm trying to do that

>  Maybe when compiling results (eg averaging scores
across seeds) we should output
for each method what proportion of datasets it completed for.

We should end up with an array of, say, scores, mixed with numbers and NA. Currently I provide command interface to get there but it does not check for completeness of data. Doing it on shinydsc when it plots makes more sense and is also more modular. The question is how good shinydsc will become (I think we've already trimmed it to a minimal features compared to what we had in mind before).
