### ISSUE TITLE
Organizing and parsing the DSC meta data

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#71]
See the proposed interface here:

https://github.com/stephenslab/dsc-wiki/blob/master/development/initial_thoughts_on_terminology_and_extraction.md#extracting-information-about-a-pipeline

> Extracting information about a pipeline:

Is `SEED = s` truly necessary? We can also return things for all seeds such that `p$[modulename]$output[[i]]` corresponds to each seed. 

Otherwise I do not have big objections for now. This is very similar to how DSC2 works now (though not the interface).

> Extracting information from a set of pipelines

My biggest objection against a flat data frame structure is what if the end product of a pipeline is not a number or not even a vector? 

Currently DSC uses a query system (implemented in Python) that allows one to search for given parameter values / ranges of values / relationships via annotation. It's very flexible yet complicated unless you are very clear about what you want. With the `module` design we will no longer needs this feature because every parameter combination is named. I'm still not sure if it is a good idea (will discuss in #68 ). But if that does happen, the whole process is a lot easier -- each module will have a definite set of output that differs only in seed, a problem that R can well manage. Still I'm not very familiar with modern R packages such as stringr / dplyr and learning them is not my current priority as I do not use R for data handling. It'd be great if either @pcarbo or @jdblischak can take a lead from here.

**Comment by gaow** [comment]
I think I should show in full what the meta data looks like based on one example under the current terminology and logic. This may help understanding how the annotation step works. I'll choose ASH for example as it involves 2 types of end of sequences.

The example is:  https://stephenslab.github.io/dsc-wiki/doc/tutorials/Intermediate_R_1.html#DSC-Specification  

Recall that we run 2 DSC sequences:

```
simulate * shrink * beta_score, 
simulate * shrink * pi0_score
```

You can understand the meta-data being an RDS file of an R list of multiple data-frames. It's in fact Pickle file containing multiple Pandas data-frames that has a query interface so I can apply annotations using Python. But it's straightforward to translate the logic to R directly using some R/SQL interface. 

There are two types of data-frames in the meta-data RDS file.

## Master meta data frames

Master data for `pi0_score`
```
dat$master_pi0_score
  simulate_name simulate_id shrink_name shrink_id pi0_score_name pi0_score_id
0     datamaker          13      runash         7      score_pi0           16
1     datamaker          14      runash         8      score_pi0           17
2     datamaker          15      runash         9      score_pi0           18
3     datamaker          13      runash        10      score_pi0           19
4     datamaker          14      runash        11      score_pi0           20
5     datamaker          15      runash        12      score_pi0           21
```
Master data for `beta_score`
```
dat$master_beta_score
  simulate_name simulate_id shrink_name shrink_id beta_score_name beta_score_id
0     datamaker          13      runash         7      score_beta             1
1     datamaker          14      runash         8      score_beta             2
2     datamaker          15      runash         9      score_beta             3
3     datamaker          13      runash        10      score_beta             4
4     datamaker          14      runash        11      score_beta             5
5     datamaker          15      runash        12      score_beta             6
```

## Module meta data frames
Here a Module means one computational step, such as `datamaker`, `runash`, `score_beta` and `score_pi0` in this example:

### `datamaker` meta data frame

```
> names(dat$datamaker)
[1] "step_id"   "depends"   "return"    "seed"      "max_pi0"   "g"        
[7] "nsamp"     "betahatsd" "min_pi0"


> dat$datamaker[, c('step_id', 'depends', 'return', 'seed', 'max_pi0', 'min_pi0', 'nsamp')]
  step_id depends      return seed max_pi0 min_pi0 nsamp
0      13     NaN datamaker_1    1       1       0  1000
1      14     NaN datamaker_2    2       1       0  1000
2      15     NaN datamaker_3    3       1       0  1000
```
Here I'm only showing you a few columns to get the big picture. `depends` and `return` columns are most important. `depends` values are ID's of previous instances it depends on. You can understand this as input file. `return` values are file names that the instance generates (may or may not be RDS file but if we work exclusively with R then these will be RDS files). For example the first row of this table is one instance of `datamaker` that takes no input data (`depends` is `NaN` -- cannot make `NA` in R but you get the idea), and generates `datamaker_1`, an RDS file output. Other columns are just parameter values.

## `runash` meta data frame

```
$runash
  step_id depends               return   mixcompdist
0       7      13 datamaker_1_runash_1      'normal'
1       8      14 datamaker_2_runash_1      'normal'
2       9      15 datamaker_3_runash_1      'normal'
3      10      13 datamaker_1_runash_2 'halfuniform'
4      11      14 datamaker_2_runash_2 'halfuniform'
5      12      15 datamaker_3_runash_2 'halfuniform'
```

Take a look at the first row for example. The return name `datamaker_1_runash_1` is very much self-explanatory: it's `(datamaker_1, runash_1)` so apparently it depends on `datamaker_1`. Our query uses `depends` value though. For example, the first row depends on ID = 13, which is found in the first row of the `datamaker` table.

## `score_beta` and `score_pi0` data frames

```
$score_beta
  step_id depends                            return
0       1       7 datamaker_1_runash_1_score_beta_1
1       2       8 datamaker_2_runash_1_score_beta_1
2       3       9 datamaker_3_runash_1_score_beta_1
3       4      10 datamaker_1_runash_2_score_beta_1
4       5      11 datamaker_2_runash_2_score_beta_1
5       6      12 datamaker_3_runash_2_score_beta_1

$score_pi0
  step_id depends                           return
0      16       7 datamaker_1_runash_1_score_pi0_1
1      17       8 datamaker_2_runash_1_score_pi0_1
2      18       9 datamaker_3_runash_1_score_pi0_1
3      19      10 datamaker_1_runash_2_score_pi0_1
4      20      11 datamaker_2_runash_2_score_pi0_1
5      21      12 datamaker_3_runash_2_score_pi0_1
```

Take the first line of `score_beta` for example. The ID of this instance is ID = 1. From return which is `(datamaker_1, runash_1, score_beta_1)` the dependency relationship is self-evident. Still via `depends` ID = 7 it tracks to the first line of `runash` data frame, which again depends on ID = 13 that tracks back to the first line of `datamaker` that has ID = 13. 

So in sum, the file `datamaker_1_runash_1_score_beta_1.rds` is generated by instance No. 13, followed by instance No. 7, followed by instance No. 1. This is exactly what's the first line in `master_beta_score` has:

```
  simulate_name simulate_id shrink_name shrink_id beta_score_name beta_score_id
0     datamaker          13      runash         7      score_beta             1
```

## How does a query work?

Suppose I want to get `score_beta` with `seed = 1` in `datamaker` and `mixcompdist = "normal"` in `runash` . So starting with `seed = 1` in `datamaker` you find `step_id =13` the only fit. And using `depends = 13` and `mixcompdist = "normal"` you find in `runash` `step_id = 7` the only fit. And using `depends = 7` you find in `score_beta` the first line the only fit, that leads to output `datamaker_1_runash_1_score_beta_1.rds`, whose file name can also tell you where it comes from. This part is currently done with a query language. This file will also correspond to one line in the `master_beta_score` table as previously pointed out.

Imaging you run with only `mixcompdist = "normal"` you'll get 3 file names each corresponding to a seed.  You can do whatever you like with them. For example you can use R to load the 3 files, get the score from each file (a single value) and put them in a vector called `mse`. The `shinydsc` app essentially is a graphic interface to this query language that also extracts the data and make some plots.

With `master_beta_score` in place you can also imaging making data frames for single numeric output, as proposed in this ticket: just matching the values with those ID's. 

## How can we not need any queries? 

The only way I can think of for now is to use fix set of parameters per module, giving them the same name. In that case for example `runash` will become `runash_halfunif` and `runash_normal`. Then there is no need to query tables other than `master_*`. One can just query in `master_*` for these very specifc module names, and use the `step_id` associated with them to locate in non-master tables the output file name, and load them. This is totally doable with basic R as no query is needed, although making them into one single nice data frames still will require some R skills.

**Comment by stephens999** [comment]
thanks @gaow. THis is really useful. Can you clarify, in general, things like:
there is one "master" meta data frame for each ... what? For each DSC? something else?

there is one "module" meta data frame for each.. what? For each module? Or for each "block" in the DSC yaml? Or ...?

**Comment by gaow** [comment]
> there is one "master" meta data frame for each ... what? For each DSC? something else?

First I apologize I'm using the old terminology. Each master meta frame corresponds to a DSC sequence ending with a different block. For example:

```
A * B * C
```
will result in a master meta data `master_C` that lists all instances C generates and all its upstream instances that leads to it (here involving B and A)

```
A * B * D
```
Will result in another master meta data `master_D`.

However if the last block is the same, for example:

```
A * B * C, A * C
```
Then these 2 sequences will result in one `master_C` with some rows in it having NA for `B` related columns.

> there is one "module" meta data frame for each.. what? For each module? Or for each "block" in the DSC yaml? Or ...?

This is for each executable in the DSC YAML, which I currently call them `step`. You can perhaps infer it already from their names, eg, datamaker, runash, score_*.

**Comment by stephens999** [comment]
thanks again.

What does the annotation step do now?
Is it actually running a query? 
Or is it adding or modifying the meta-data?

I thought from the name "annotation" it was modifying the meta data, but now I'm not so sure.

**Comment by gaow** [comment]
It modifies meta-data, in a sense, by adding additional information to it. Yet this information is not written back to this meta-data file. It will create a separate file as a result of running a query. Take the example above, the annotation file would look like:

```yaml
I_want_these_runs:
   simulate:
      seed: 1
   runash:
      mixcompdist: normal
```

By default it will run for both `master` tables. Take `score_beta` for example you therefore end up having a separate RDS file that is an R list looks like:
```r
$I_want_these_runs
[1] datamaker_1_runash_1_score_beta_1.rds
````

This again is stored in a separate file that shinydsc can read. Here `I_want_these_runs` is called a *tag*. You can imaging having a non-trivial query where under each of these tags there are very many RDS file names. One can add as many annotation tags as possible this way. Part of the job of shinydsc was to call `dsc -e` to extract the particular quantities from these RDS files given user specified tags and pipeline variables (return variables in the current terminology).

**Comment by stephens999** [comment]
@gaow can i double check whether these files are separate from files that store dependencies
in the DAG for job creation etc.

For example, does the DAG use the Depends information here?
Or not?

**Comment by gaow** [comment]
No this information is not directly used for job creation. Here `depends` means what sequence has led to the output file at given stage. What file goes into it is vague. In creating the jobs, for each step we have stored internally the exact input files that it takes and the output it produces. That only involve those files a step actually needed. Same as with `make` or `snakemake` logic we create DAG based on strict file dependencies, not the sequence that leads to a step.

**Comment by stephens999** [comment]
it seems we basically have a relational database but where some of the records are structured in a hierarchical (tree-like) fashion. Do any of you have previous experience with dealing with relational databases and trees? @gaow @pcarbo

**Comment by stephens999** [comment]
Other questions - a related system is the R package "batchExperiments". @gaow can you look at that and see how easy it would be to see how they deal with it? (I think they use SQL).

**Comment by stephens999** [comment]
@gaow it seems that each row of the master table corresponds to 
a pipeline instance, and the columns contain which module instances occured in that pipeline instance. Is that correct? (I have slightly updated terminology document to define module instance etc).

As I understand it, module instances in a DSC are connected by a tree (each module instance has a parent). So this table is storing the tree information as a flat table structure.
Meanwhile the other tables also  store the tree information by storing the parent of each module
instance. Is this correct?

**Comment by gaow** [comment]
@stephens999 yes you are correct about how master table and other tables work. The hierarchical part is reflected in `depends`. You can imaging expending the hierarchical relationship via SQL join-like statement `SELECT ... FROM table_1 INNER JOIN table_2 ON table_1.depends = table_2.step_id WHERE ...`. This is why I thought it should not be hard to have some R implementation of queries via SQL interface. Of course if no annotation is needed in our later designs there is no need for queries.

I've used SQLite in various occasions in the past though I cannot claim expert on it.

The R package https://github.com/mllg/batchtools is the successor of batchExperiments. This vignette is particularly relevant:

http://mllg.github.io/batchtools/articles/v11_ExampleExperiment.html

It is not clear to me though whether any query is involved when it comes to result collection. It seems they just listed all possible combinations in one flat table. The `reduceResults()` function only loads RDS files.

**Comment by stephens999** [comment]
I'm not sure why you say "if no annotation is necessary no queries will be
necessary".
to me those are two different things...
(I guess I see queries as extracting information from the data base, which
of
course will be necessary one way or another!)

**Comment by gaow** [comment]
Well, annotations are conditions that defines the `WHERE` statement of queries. However if we do have a way to name each pipeline instance then this `WHERE` statement becomes very simple, something like `WHERE instance = 'name'`. Yes you are right we need query one way or another. *Annotations* is just a complicated yet flexible way to compose queries. I guess at this point we should discuss:

1. If this meta data structure can be improved. 
2. What can we do to make query simpler.

**Comment by pcarbo** [comment]
@gaow, Is it ever the case in a DSC that one block directly depends on more than one block? For example, the run statement `A * B * C` corresponds to a function evaluation of the form `C(z,B(y,A(x)))`; e.g. the output of `A(x)` is passed as an input to function/module `B`, and 'y' and 'z' are additional parameters that do not depend on any block. That means that the dependency relationships between module instances can always be represented linearly (e.g., as a linked list), whereas in general the relationships would have to be represented as a tree data structure.

**Comment by gaow** [comment]
@pcarbo yes one *block* (still calling it a block to answer your question) can depend on more than one other block -- like you said it's a tree. The catch is that the dependencies are always found upstream of a block, so even though `run` statement alone does not define dependency; one can at infer that `C` depends on `A` or `B` or `A and B` in your example. It is the run statement plus the `$` variables (`input` variables in your comment on #68) that uniquely defines dependency.

**Comment by pcarbo** [comment]
Thanks, that's helpful. (I'll try to use "module" instead of "block", following Matthew's preference.) So implicitly when you have a run statement such as `A * B * C`, it is better to think of it as the evaluation sequence `C(A(x),B(A(x)))` to make explicit the dependency between `A` and `C`.

**Comment by stephens999** [comment]
@gaow I think that in the tables the term "depends" is used to indicate
the immediate prior (parent) module instance.

If that is correct I think it would be
better to use the term parent.

**Comment by gaow** [comment]
@pcarbo Yes that's what holds for the Quick Start tutorial example the location parameter estimation. Just a pointer that there might be situations when `A * B * C * D` is in fact `D(C(A(x)), B(A(x)))` -- with the `run` statement plus logic inside the modules one should be able to tell this evaluation sequence in this context.

**Comment by gaow** [comment]
@stephens999 sure. I've added a table in this file to record what we've agreed on (and what's pending):

https://github.com/stephenslab/dsc-wiki/blob/master/development/initial_thoughts_on_terminology_and_extraction.md#terminology-finalized

Do you think we want to change `master` to `pipeline` in the meta data?

**Comment by stephens999** [comment]
Thanks @gaow

It is a little tricky to say whether I agree/disagree with the old-new
terminology correspondence, as I was never sufficiently clear on the old
terminology.

Regarding "multi-module", let's leave this for now.
Let's just agree that the module name does not always uniquely define the
module - two modules can have the same name (and same executable) but
differ through different parameter values, and that we want to be able to
deal
with this situation.

I want to tentatively
suggest we have things defined well enough that we can focus
discussion now on the tables (meta data) that you are storing
and whether they can be improved.

**Comment by gaow** [comment]
@stephens999 I agree -- let's focus on the meta data and see what we can do to improve it, then see how they are connected to the new terminology. Components of the old terminology are in fact reflected in the meta data as you can probably guess, so whatever added to / deleted from the meta data would indicate non-correspondence between old and new. After finalizing this table we'll be in a better position to discuss syntax changes.

Again, currently `dsc -x` command generates this table and run everything; `dsc -a` command will take queries (in the format of annotation files) and output the collections of target RDS (or other formats) files, and the shiny interface will call `dsc -e` to extract pipeline variables from those target RDS files. I'm re-iterating this, because another way to get rid of annotations is to replace `dsc -a` and `dsc -e` by some R functions. We can at least starting to design interface of these functions. I'm personally comfortable with `dsc -a` and `dsc -e` perhaps mostly because I'm personally uncomfortable to do complicated logic in R ...

**Comment by stephens999** [comment]
what does the file
datamaker_1_runash_1_score_beta_1.rds
contain?
only the output from the final module instance (score_beta_1)
or all output from all modules instances in the sequence?

**Comment by stephens999** [comment]
what do you use/need the master table for?

**Comment by gaow** [comment]
The file datamaker_1_runash_1_score_beta_1.rds only has the output from the final module. The master table provides a short cut to finding the name of its parent. It also can potentially be used to store single number output such as a score, by appending columns to it.

**Comment by stephens999** [comment]
each of these meta tables contains information about module instances. 

Roughly, you use one table for each set of "parameter-concordant" modules, which means modules
that take the same set of parameters. (Actually I don't know exactly your rule for putting
a set of modules in the same table, but I guess they might have something to do with
being defined in the same YAML block in the DSC file?)

Conceptually one could have a single table, with one row for each module instance:

id   parent    name     exec     param returns

where param would refer to a parameter set id defined in a different table.

eg

id var_name value
1    n         10
1    K          2
2    n         1000
2    K          2
3    min_pi0   0
3    max_pi0   1
3    n          100
3    g          AsIs(normalmix(xxx))

etc.

This would have the advantage of reducing the number of tables (although each one would be bigger) and potentially (at least conceptually) simplifying some queries. 
I can also understand you might have reasons to prefer the current set-up...

Your current tables are also based solely around module instances. It might be cleaner to
have two tables, one for module definitions, and another for module instances.

Say
module definitions table:

id     name     exec    param
1      normal   normal.R    1
2      normal   normal.R   2
3     trimmean     trimmean.R      7

[note that in this table there will be a 1-1 map between id and  the combination (name,param);
that is (name, param) uniquely defines a module]

and module instances table

id    module_def  seed parent   return   
1     1                    1       x            y
2      1                    2      x            y

here module_def is a foreign key referring to id in the module definitions table.

These are just thoughts for discussion for now. I do think this latter makes sense as a principle,
although it is storing the same information as you currently have.

**Comment by gaow** [comment]
Thanks @stephens999 I get your proposal. 

> you use one table for each set of "parameter-concordant" modules, which means modules
that take the same set of parameters.

This is not exactly the case. I in fact use one table per executable. Even of two executables take exactly the same set of parameters they'll end up in different tables.

The current setup is good for SQL-like queries. But if we want to create R functions to extract results we may want to re-organize what these tables look like. 

Reducing the number of tables, or breaking module table into definition and instance tables are not obvious advantage to me unless it does simplify queries. To me it is irrelevant how "friendly" or "clear" the meta data looks to human eyes because users should not need to understand how meta data is organized. Rather they need a friendly and intuitive interface that extract information they want. Ideally users should not need to even look into the meta data if our extraction interface is good enough. As developers I think we should only reorganize meta data structure if it helps implementing the interface. So my suggestion is perhaps we can think of data extraction interface, a discussion involving other savvy R developers @pcarbo and @jdblischak -- but perhaps you've already have something of this respect in mind when you propose this new data structure?

**Comment by stephens999** [comment]
no, you are right, i do not think we need any changes here to make
the interface work nicely (for now).

Reorganizing this might make software
maintenance easier (eg easier for other developers
to understand the logic and contribute) but let's focus on improving
extraction interface for now.
