### ISSUE TITLE
About .alias: what it does and if we want a different term for it 

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#78]
There are two aims for `.alias`:

1. "Pack" variables to lists or dictionary. Suppose a module script involves variables `g`, `args`
where args is a `list(min_pi0=0,max_pi0=1, nsamp=1000)`
We can use
```
.alias: args = List(min_pi0, max_pi0,nsamp)
```
To pack variables other than `g` into a list `args`. `args = list()` is a shorthand for packaging all in.

2. other than packing parameters to dictionary / List,  it is also an opportunity to overwrite parameter names that a user dislike but does not want to change it in the code, for example

```input:
  gamma: $x
  .alias: g = gamma
```
Because in the code one uses variable `g` which is not an informative name. We therefore offer a chance to fix here.

**Comment by stephens999** [comment]
Ok, now I understand this I may be ok with it.
I was confused by the list() shorthand. But when done longhand it makes logical sense to me, and the shorthand is fine and potentially useful now explained to me.
