### ISSUE TITLE
Global variables in DSC

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#81]
In this ticket https://github.com/stephenslab/dsc2/issues/70#issuecomment-298966298 I showed the use of DSC global variable:

```
DSC:
  variable:
     some_var:  '...'
```

I've agreed with @stephens999 that we still would use `$` symbol instead of `$()` to access it, because it is similar to pipeline variable in scope. However the difference here is that these variables are constants. 

There are two points to discuss:

1. Do we need these global variables? I vote for Yes because I'm sure there will be shared parameters among all modules, for things such as `path` and computational environment configurations (we've not talked about execution on remote computers eg RCC). 
2. How should they be distinguished? We are not forcing any conventions on these variables (eg all capital letters) and we'll check and raise error if there is a name conflict with pipeline variables. Is it good enough?

**Comment by stephens999** [comment]
are these constant variables? so can't be output?

**Comment by gaow** [comment]
Yes these are constants. User cases I can think of are typically strings such as file names, paths, computational environment settings (walltime, mem, etc -- though we'll have global defaults in separate config file just like snakemake), or a particularly meaningful choice of sets of parameters that we want to treat as constants.

**Comment by stephens999** [comment]
i'm good with these. How about `global:` instead of `variable:` as keyword?

**Comment by gaow** [comment]
Agreed! 

But what is the behavior when there is a conflict (my question 2 above) with pipeline variables? Report an error or warning? I guess an error? If you think the same then we're good to close hte issue.

**Comment by stephens999** [comment]
yes, I agree, global variables must have different names than pipeline
variables.

**Comment by stephens999** [comment]
... and can't be outputs from module?

**Comment by gaow** [comment]
Yes any pipeline variable will result in a conflict. I'll ensure that's checked for. Closing this issue now.
