### ISSUE TITLE
Companion R package

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#87]
This is related to #86 and we actually had some form of companion packages before #43. At least this package will serve 3 purposes:

1. Define a more generic data communication format #86 
2. Help extracting the actual data (along the lines of #71 which is a very early discussion but we have been moved forward a lot since that). I've communicated with @pcarbo on how it supposed to wrap `dsc-query` as an R function and do additional work.
3. As @pcarbo and I have discussed today, we need a better `R()` operation implementation for DSC script that loads arbitrary user provided function and return atomic elements, vectors or list of vectors .
4. Additionally currently I've got some glue R codes that I hard-coded to some DSC util functions that we better move to this R package and we can take from there. 

I order these bullets by roughly the date we discuss them, but the priority should be 2 > 3 > 4 > 1. Particularly I think we can move to 2 right now!

@pcarbo could you kindly start a new repo, create a package with a single function called `dsc_query()` (or other names) you see fit, and make it say "hello world?". I'll start wrapping `dsc-query` to it, and we'll then see how we will use native R routines to batch load data in R (hopefully in parallel) -- what do you think? Wei and I had done a similar wrapper in the [`shinydsc`](https://github.com/stephenslab/shinydsc) package but that's an old version of implementation and is no longer very relevant at this point.

**Comment by pcarbo** [comment]
@gaow A couple of followup questions about Item 2:

+ Is it okay if we create the R package in this repo?

+ So I better understand what we are trying to accomplish, can you share with me an example of the types of data that would be loaded?

**Comment by gaow** [comment]
> Is it okay if we create the R package in this repo?

Sure

>  can you share with me an example of the types of data that would be loaded?

Yes:

https://stephenslab.github.io/dsc-wiki/playground/Q1.xlsx

You see there are names of files on the last column that contains variable `mse` that we need.

**Comment by gaow** [comment]
RE 2:  this bash wildcard trick is helpful for specifying multiple fields:

```
[GW] echo simulate.{n,p,df}
simulate.n simulate.p simulate.df
```

I'm wondering when using the R interface if there are similar tricks we can take advantage of when making queries.

**Comment by pcarbo** [comment]
@gaow `paste("simulate",c("n","p","df"),sep=".")` achieves the same thing.

**Comment by gaow** [comment]
Thanks @pcarbo 

RE identifying what data to extract -- currently we use column names, rather than some separate information (such as meta data text `#` in output files). It is a bit ugly, but since is meant to be used internally, having an internal rule on column names makes our life a bit easier. 

Column names of the results will look like, eg, 

```
simulate
simulate.true_mean.output
simulate_n
simulate_true_mean
estimate
estimate.output
mse.mse.output
```

There are 3 types of column names: 

1. conventional `module_parameter` column name
2. `group` name as column name
3. `module.variable.output` or just `module.output`

Only 3 is relevant to our data extraction problem. When it is `module.output` (single dot separated), it means we only want to get the output file name. No variable needs to be extracted. When it is `module.variable.output` (separated by 2 dots, ending with `.output`) it means for this column the variable `variable` will have to be extracted. Hopefully this convention clear enough.

**Comment by gaow** [comment]
Now back to action item 23

>  we need a better DSC `R()` operation implementation that loads arbitrary user provided R code and return atomic elements, vectors or list of vectors. 

Basically, DSC will parse whatever inside `R(...)` to `dscrutils:run_r(...)`, which runs the code chunk `...` and return to either one of the 3 formats:

1. `1,2,3,4,5`: a comma separated string of atomic, non-vector elements -- corresponding to R's vector
2. `(1,2), (3,4), (5,6)`: string of vectors -- corresponding to R's list of vectors. 
3. Most importantly, to what extend we handle exceptions from type check:
   1. single column data-frame or single-row matrix (I think they should be acceptable)
   2. deal with NULL values (I think we should just drop them)
   3. empty return ie vectors or lists of length zero (I think we should throw an error)

**Comment by pcarbo** [comment]
@gaow Does it accept non-numeric vectors? logical, character, _etc_?

**Comment by gaow** [comment]
@pcarbo Yes it should -- and they should be converted to strings verbatimly.

**Comment by pcarbo** [comment]
@gaow And what happens if the input is not in any of the accepted formats? Should `run_r` throw an error?

Also, `run_r` is not a great name… to general. I'm think `dsceval`. Is that okay?

**Comment by gaow** [comment]
Thanks @pcarbo yes surely I not saying we should use `run_r`. `dsceval` sounds great. But should we make all function names consistently `dsc_*`? For this case `dsc_eval` I guess?

> And what happens if the input is not in any of the accepted formats? Should run_r throw an error?

I guess a try .. catch around `eval(input)` would be enough to throw any messages if input is bad R code, right?

**Comment by pcarbo** [comment]
> But should we make all function names consistently dsc_*?

Hard to say… we only have two functions right now. :) 

> I guess a try .. catch around eval(input) would be enough to throw any messages if input is bad R code, right?

@gaow Yes, but more than that---as you described above, we will only convert some data structures to strings. For example, `c(1,2,3)` is acceptable, but `list(list(1,2),list(3,4))` (a list of lists) is not. So should `dsceval(list(list(1,2),list(3,4)))` return an error?

**Comment by gaow** [comment]
> Hard to say… we only have two functions right now. :)

I was thinking we might want to add some data viz R functions down the line ...

> should dsceval(list(list(1,2),list(3,4))) return an error?

I see. Yes this is related to my Point 3 above "to what extend do we handle bad outputs" (our confusion is the term `input` and `output` -- here this i'd refer to `output`). For this case, do we want to interpret as `list(c(1,2), c(3,4))`, or we want to throw an error? Somewhere we have to draw a line (same comment you made for a related problem in `dsc_query`!). For this case returning `(1,2),(3,4)` seems reasonable. I've updated [this thread](https://github.com/stephenslab/dsc2/issues/87#issuecomment-367689874). Do you think we should stick to these types? I would also agree if you deem these too complicated to implement.

**Comment by pcarbo** [comment]
> Somewhere we have to draw a line.

@gaow My suggestion: to keep things simple, let's allow atomic objects (*i.e.*, vectors) and lists of atomic objects (*i.e.*, lists of vectors), otherwise throw an error. We can always revise this behaviour in the future if there is the need. Is that okay with you?

**Comment by gaow** [comment]
Agreed. Thanks @pcarbo !

**Comment by gaow** [comment]
All done except for 1, which we have agreed to implement if there is demand down the line (to communicate with Matlab, or serious complains about `rpy2` installation / performance for R<->Python communications).
