### ISSUE TITLE
Use `Rmd` files as module executables

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#90]
This might be an appealing feature to have for those who work with `Rmd` files a lot: we should allow module executable scripts to be loaded from `Rmd` files. I do not use `Rmd` files so I'd need experts eyes on this one, but I suppose [something like this](http://rstudio-pubs-static.s3.amazonaws.com/12734_0a38887f19a34d92b7311a2c9cb15022.html) (also discussed [here](https://github.com/rstudio/rmarkdown/issues/1135) but I cannot seem to find it easily in `rmarkdown` 1.7) can be used?

**Comment by jdblischak** [comment]
@gaow Does `knitr::purl` do what you need?

https://www.rdocumentation.org/packages/knitr/versions/1.19/topics/knit

**Comment by pcarbo** [comment]
@jdblischak You beat me to it:`knitr::purl("myanalysis.Rmd")`.

**Comment by gaow** [comment]
Great that should do it. Thanks @jdblischak and @pcarbo
