### ISSUE TITLE
Nested tuple input

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#91]
Currently nested tuple is perhaps the most complex input we allow from the interface, without having ot use `raw`. Right now nested tuple is misbehaved for R. eg:

```
n: (100, (200,300)), (400, 500, 600)
```
The first one is nested tuple, which will cause problem in R. We should specifically "flatten" tuples in R, eg make it `(100,200,300)`, before passing to R, or try harder with `c(100,c(200,300))`  But the problem remains that queries will be inconsistent -- that in one setting `n` has 3 elements and another has 2 elements. There may be user cases for this, but DSC query will have difficulty deciding whether to split to 2 or to 3 elements.

**Comment by gaow** [comment]
A cleaner solution would be disable nested tuple, and support only up to tuple level. We will flatten whatever inside tuples. I personally use nested tuples heavily in Python, but I assume that's when I will have to use `raw` instead for interface to my Python codes.

**Comment by pcarbo** [comment]
@gaow A tuple in Python seems like a very complicated data structure; I suggest that tuples (or lists in R) need to be defined using `raw()`. Otherwise, I see this raising a lot of confusion and errors.

**Comment by gaow** [comment]
Great, let's use `raw` for it.

**Comment by pcarbo** [comment]
@gaow But vectors are allowed, right? (*i.e.*, non-nested tuples in which each element is a character, numeric or logical?

**Comment by gaow** [comment]
@pcarbo Yes, I guess we should say we support objects that returns `True` for R's `is.atomic()` ?

**Comment by pcarbo** [comment]
@gaow Yes, I think that is a reasonable approach. More precisely, an object `x` can be defined in DSC without raw if and only if `is.atomic(x) & !is.null(x)` is `TRUE`. Correct?

**Comment by gaow** [comment]
I think this is the intention, at least. I will have to create unit tests for various representations for missing value though I think my code intended to deal with them properly ..
