### ISSUE TITLE
Parameter combination logic

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc2#92]
By default we adopt Cartesian product logic when combining parameters. This behavior can be adjusted either grouping parameters together:

```
n_df: (100,2), (1000, 4)
```

Or apply `@FILTER`:

```
n: 100, 1000
df: 2, 4
@FILTER: (n = 100 and df = 2) or (n = 1000 and df = 4)
```

A proposed syntax is:

```
(n, df): (100, 2), (1000, 4)
```

I will implement this behavior if deemed reasonable.

**Comment by stephens999** [comment]
I like the proposed syntax, at least for scalar parameters.

**Comment by pcarbo** [comment]
@gaow Seems reasonable to me.

**Comment by gaow** [comment]
This is now supported, though need more unit tests to cover all steps this change may have affected.
